/*
 * This file is generated by jOOQ.
 */
package com.q3js.http.jooq;


import com.q3js.http.jooq.tables.Server;
import com.q3js.http.jooq.tables.records.ServerRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ServerRecord> SERVER_PKEY = Internal.createUniqueKey(Server.SERVER, DSL.name("server_pkey"), new TableField[] { Server.SERVER.ID }, true);
}
