/*
 * This file is generated by jOOQ.
 */
package com.q3js.http.jooq.tables.pojos;


import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Server implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private Integer port;
    private String status;
    private String ipAddress;
    private OffsetDateTime createdAt;

    public Server() {}

    public Server(Server value) {
        this.id = value.id;
        this.name = value.name;
        this.port = value.port;
        this.status = value.status;
        this.ipAddress = value.ipAddress;
        this.createdAt = value.createdAt;
    }

    public Server(
        Integer id,
        String name,
        Integer port,
        String status,
        String ipAddress,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.name = name;
        this.port = port;
        this.status = status;
        this.ipAddress = ipAddress;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>server.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>server.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>server.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>server.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>server.port</code>.
     */
    @NotNull
    public Integer getPort() {
        return this.port;
    }

    /**
     * Setter for <code>server.port</code>.
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * Getter for <code>server.status</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>server.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>server.ip_address</code>.
     */
    @NotNull
    @Size(max = 45)
    public String getIpAddress() {
        return this.ipAddress;
    }

    /**
     * Setter for <code>server.ip_address</code>.
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for <code>server.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>server.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Server other = (Server) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.port == null) {
            if (other.port != null)
                return false;
        }
        else if (!this.port.equals(other.port))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        }
        else if (!this.ipAddress.equals(other.ipAddress))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.port == null) ? 0 : this.port.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.ipAddress == null) ? 0 : this.ipAddress.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Server (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(port);
        sb.append(", ").append(status);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
