/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq.tables.records;


import com.q3js.jooq.tables.Server;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Inet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServerRecord extends UpdatableRecordImpl<ServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>server.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>server.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>server.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>server.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>server.ip_address</code>.
     */
    public void setIpAddress(Inet value) {
        set(2, value);
    }

    /**
     * Getter for <code>server.ip_address</code>.
     */
    @NotNull
    public Inet getIpAddress() {
        return (Inet) get(2);
    }

    /**
     * Setter for <code>server.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>server.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServerRecord
     */
    public ServerRecord() {
        super(Server.SERVER);
    }

    /**
     * Create a detached, initialised ServerRecord
     */
    public ServerRecord(Integer id, String name, Inet ipAddress, OffsetDateTime createdAt) {
        super(Server.SERVER);

        setId(id);
        setName(name);
        setIpAddress(ipAddress);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ServerRecord
     */
    public ServerRecord(com.q3js.jooq.tables.pojos.Server value) {
        super(Server.SERVER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setIpAddress(value.getIpAddress());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
