import assert from "node:assert/strict";
import test from "node:test";
import { assemblePlayer, MAX_SKIN_LINE_LENGTH, MAX_SKIN_MAPPINGS, MAX_SKIN_TEXT_LENGTH, parseIdleFrames, parseMd3, parseSkin, parseTga, playerResourcePaths } from "./player-model.ts";
import { fetchFirstAvailable, playerSkinCandidates } from "./player-preview.ts";

function text(view: DataView, offset: number, value: string): void { for (let index=0;index<value.length;index+=1)view.setUint8(offset+index,value.charCodeAt(index)); }
function surface(name:string,x:number):Uint8Array { const size=108+12+8*3+8*3,bytes=new Uint8Array(size),view=new DataView(bytes.buffer);text(view,0,"IDP3");text(view,4,name);view.setInt32(72,1,true);view.setInt32(80,3,true);view.setInt32(84,1,true);view.setInt32(88,108,true);view.setInt32(96,120,true);view.setInt32(100,144,true);view.setInt32(104,size,true);view.setInt32(108,0,true);view.setInt32(112,1,true);view.setInt32(116,2,true);for(let vertex=0;vertex<3;vertex+=1){view.setFloat32(120+vertex*8,vertex===1?1:0,true);view.setFloat32(124+vertex*8,vertex===2?1:0,true);view.setInt16(144+vertex*8,(x+(vertex===1?1:0))*64,true);view.setInt16(146+vertex*8,(vertex===2?1:0)*64,true);}return bytes; }
function md3(names:string[],tag?:string):ArrayBuffer { const surfaces=names.map((name,index)=>surface(name,index*2)),tagBytes=tag?112:0,start=108+56+tagBytes,total=start+surfaces.reduce((sum,value)=>sum+value.length,0),bytes=new Uint8Array(total),view=new DataView(bytes.buffer);text(view,0,"IDP3");view.setInt32(4,15,true);view.setInt32(76,1,true);view.setInt32(80,tag?1:0,true);view.setInt32(84,names.length,true);view.setInt32(92,108,true);view.setInt32(96,164,true);view.setInt32(100,start,true);view.setInt32(104,total,true);if(tag){text(view,164,tag);view.setFloat32(228,0,true);view.setFloat32(232,0,true);view.setFloat32(236,5,true);for(let index=0;index<3;index+=1)view.setFloat32(240+(index*3+index)*4,1,true);}let cursor=start;for(const value of surfaces){bytes.set(value,cursor);cursor+=value.length;}return bytes.buffer; }

test("MD3 parser keeps every surface and assembly follows attachment tags",()=>{const lower=parseMd3(md3(["legs_a","legs_b"],"tag_torso")),upper=parseMd3(md3(["torso_a","torso_b"],"tag_head")),head=parseMd3(md3(["head_a","head_b"]));assert.equal(lower.surfaces.length,2);const assembled=assemblePlayer(lower,upper,head);assert.equal(assembled.length,6);assert.deepEqual(assembled.map(value=>value.part),["lower","lower","upper","upper","head","head"]);assert.equal(assembled[4].position[2],10);});
test("skin parser handles comments, case, and *off without unsafe references",()=>{const skin=parseSkin("Torso,models/players/sarge/torso // stock\ncaps,*off\n");assert.equal(skin.get("torso"),"models/players/sarge/torso");assert.equal(skin.get("caps"),null);assert.throws(()=>parseSkin("body,../secret"),/Unsafe/);});
test("skin parser bounds text, lines, and mapping count",()=>{assert.throws(()=>parseSkin("x".repeat(MAX_SKIN_TEXT_LENGTH+1)),/text exceeds/);assert.throws(()=>parseSkin(`body,models/players/${"x".repeat(MAX_SKIN_LINE_LENGTH)}`),/line exceeds/);const mappings=Array.from({length:MAX_SKIN_MAPPINGS+1},()=>"body,models/players/sarge/x").join("\n");assert.throws(()=>parseSkin(mappings),/mapping count/);});
test("appearance paths implement body, default skin, and optional separate head",()=>{assert.deepEqual(playerResourcePaths({model:"sarge",skin:"",headModel:"*visor",headSkin:"blue"}),{bodyRoots:["models/players/sarge","models/players/characters/sarge"],headRoots:["models/players/heads/visor"],headFileNames:["visor.md3"],bodySkin:"default",headSkin:"blue",separateHead:"visor"});const regular=playerResourcePaths({model:"sarge",skin:"red",headModel:"",headSkin:"blue"});assert.equal(regular.headSkin,"red");assert.equal(regular.separateHead,"");assert.throws(()=>playerResourcePaths({model:"../sarge",skin:"default",headModel:"",headSkin:""}));});
test("skin paths follow regular and separate-head naming without fallback candidates",()=>{const root="models/players/sarge";assert.deepEqual(playerSkinCandidates(root,"lower","blue"),[`${root}/lower_blue.skin`]);assert.deepEqual(playerSkinCandidates(root,"upper","blue"),[`${root}/upper_blue.skin`]);assert.deepEqual(playerSkinCandidates(root,"head","blue"),[`${root}/head_blue.skin`]);assert.deepEqual(playerSkinCandidates("models/players/heads/visor","head","red","visor"),["models/players/heads/visor/visor_red.skin"]);assert.deepEqual(playerSkinCandidates(root,"lower","hunter"),[`${root}/lower_hunter.skin`]);assert.deepEqual(playerSkinCandidates(root,"upper",""),[`${root}/upper_default.skin`]);assert.deepEqual(playerSkinCandidates(root,"head","default"),[`${root}/head_default.skin`]);});
test("animation config selects stable torso and adjusted leg idle frames",()=>{const rows=Array.from({length:25},(_,index)=>`${index<13?index*10:100+(index-13)*5} 1 1 10`).join("\n");assert.deepEqual(parseIdleFrames(rows),{upper:110,lower:105});});
test("RLE true-color TGA decodes opaque and alpha pixels",()=>{const bytes=new Uint8Array(18+1+4);bytes[2]=10;bytes[12]=2;bytes[14]=1;bytes[16]=32;bytes[18]=0x81;bytes.set([3,2,1,4],19);const image=parseTga(bytes.buffer);assert.deepEqual(Array.from(image.pixels),[1,2,3,4,1,2,3,4]);});
test("top-origin TGA rows stay top-first for renderer upload",()=>{const bytes=new Uint8Array(24);bytes[2]=2;bytes[12]=1;bytes[14]=2;bytes[16]=24;bytes[17]=0x20;bytes.set([0,0,255],18);bytes.set([255,0,0],21);assert.deepEqual(Array.from(parseTga(bytes.buffer).pixels),[255,0,0,255,0,0,255,255]);});
test("resource candidate fallback is limited to HTTP 404",async()=>{const calls:string[]=[];const fetch404ThenOk:typeof fetch=async(input)=>{calls.push(String(input));return new Response("",{status:calls.length===1?404:200});};assert.equal((await fetchFirstAvailable(["first","second"],new AbortController().signal,fetch404ThenOk)).path,"second");assert.deepEqual(calls,["/api/player-resource?q=first","/api/player-resource?q=second"]);calls.length=0;const fetch500:typeof fetch=async(input)=>{calls.push(String(input));return new Response("",{status:500});};await assert.rejects(fetchFirstAvailable(["first","second"],new AbortController().signal,fetch500),/500/);assert.deepEqual(calls,["/api/player-resource?q=first"]);});
test("MD3 parser rejects expansion and surface counts beyond format limits",()=>{const oversizedFrames=md3(["body"]),frameView=new DataView(oversizedFrames);frameView.setInt32(76,1_025,true);assert.throws(()=>parseMd3(oversizedFrames),/counts/);const oversizedVertices=md3(["body"]),vertexView=new DataView(oversizedVertices),surfaceOffset=vertexView.getInt32(100,true);vertexView.setInt32(surfaceOffset+80,4_097,true);assert.throws(()=>parseMd3(oversizedVertices),/counts/);});
test("MD3 parser rejects surface data ranges that escape their surface",()=>{const bytes=md3(["body"]),view=new DataView(bytes),surfaceOffset=view.getInt32(100,true),end=view.getInt32(surfaceOffset+104,true);view.setInt32(surfaceOffset+100,end-4,true);assert.throws(()=>parseMd3(bytes),/layout/);});
