import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { deflateRawSync } from "node:zlib";
import { extractPk3Entry, indexPk3, isPathContained, PlayerAssetStore, validatePlayerQpath } from "./player-assets.ts";

function crc32(buffer:Buffer):number { let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let bit=0;bit<8;bit+=1)crc=(crc>>>1)^(crc&1?0xedb88320:0);}return(crc^0xffffffff)>>>0; }
function zip(files:Record<string,string>,deflate=false):Buffer { const local:Buffer[]=[],central:Buffer[]=[];let offset=0;for(const[name,value]of Object.entries(files)){const filename=Buffer.from(name),plain=Buffer.from(value),body=deflate?deflateRawSync(plain):plain,checksum=crc32(plain),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(deflate?8:0,8);header.writeUInt32LE(checksum,14);header.writeUInt32LE(body.length,18);header.writeUInt32LE(plain.length,22);header.writeUInt16LE(filename.length,26);local.push(header,filename,body);const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50);directory.writeUInt16LE(deflate?8:0,10);directory.writeUInt32LE(checksum,16);directory.writeUInt32LE(body.length,20);directory.writeUInt32LE(plain.length,24);directory.writeUInt16LE(filename.length,28);directory.writeUInt32LE(offset,42);central.push(directory,filename);offset+=header.length+filename.length+body.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directory,end]);}
test("stored and deflated PK3 entries extract",()=>{for(const compressed of [false,true]){const bytes=zip({"models/players/test/lower.md3":"model"},compressed),entry=indexPk3(bytes).get("models/players/test/lower.md3");assert.ok(entry);assert.equal(extractPk3Entry(bytes,entry).toString(),"model");}});
test("stored payload and deflated CRC corruption fail closed",()=>{const name="models/players/test/lower.md3";const stored=zip({[name]:"model"});stored[30+Buffer.byteLength(name)]^=1;const storedEntry=indexPk3(stored).get(name);assert.ok(storedEntry);assert.throws(()=>extractPk3Entry(stored,storedEntry),/Malformed or corrupt ZIP entry/);const deflated=zip({[name]:"model"},true),directory=deflated.indexOf(Buffer.from("PK\x01\x02","binary"));deflated.writeUInt32LE((deflated.readUInt32LE(directory+16)^1)>>>0,directory+16);const deflatedEntry=indexPk3(deflated).get(name);assert.ok(deflatedEntry);assert.throws(()=>extractPk3Entry(deflated,deflatedEntry),/disagrees with central directory/);});
test("unsupported ZIP compression methods are rejected",()=>{const name="models/players/test/lower.md3",bytes=zip({[name]:"model"}),directory=bytes.indexOf(Buffer.from("PK\x01\x02","binary"));bytes.writeUInt16LE(12,directory+10);const entry=indexPk3(bytes).get(name);assert.ok(entry);assert.throws(()=>extractPk3Entry(bytes,entry),/Unsupported ZIP entry/);});
test("local ZIP headers must agree with the central directory",()=>{const name="models/players/test/lower.md3";for(const mutate of [(bytes:Buffer)=>bytes.writeUInt16LE(8,8),(bytes:Buffer)=>bytes.writeUInt16LE(8,6),(bytes:Buffer)=>bytes.writeUInt32LE(1,14),(bytes:Buffer)=>bytes.writeUInt32LE(1,18),(bytes:Buffer)=>bytes[30]^=1]){const bytes=zip({[name]:"model"}),entry=indexPk3(bytes).get(name);assert.ok(entry);mutate(bytes);assert.throws(()=>extractPk3Entry(bytes,entry),/disagrees/);}const badSignature=zip({[name]:"model"}),badEntry=indexPk3(badSignature).get(name);assert.ok(badEntry);badSignature.writeUInt32LE(0,badEntry.offset);assert.throws(()=>extractPk3Entry(badSignature,badEntry),/Malformed ZIP local entry/);const descriptor=zip({[name]:"model"}),directory=descriptor.indexOf(Buffer.from("PK\x01\x02","binary")),entry=indexPk3(descriptor).get(name);assert.ok(entry);descriptor.writeUInt16LE(8,6);descriptor.writeUInt16LE(8,directory+8);descriptor.fill(0,14,26);entry.flags=8;assert.equal(extractPk3Entry(descriptor,entry).toString(),"model");});
test("PK3 package precedence is descending and ahead of loose files",async()=>{const root=await mkdtemp(path.join(tmpdir(),"q3-preview-"));try{const base=path.join(root,"baseq3");await mkdir(path.join(base,"models/players/test"),{recursive:true});await writeFile(path.join(base,"models/players/test/lower.md3"),"loose");await writeFile(path.join(base,"pak0.pk3"),zip({"models/players/test/lower.md3":"zero"}));await writeFile(path.join(base,"z-custom.pk3"),zip({"models/players/test/lower.md3":"custom"},true));const store=await PlayerAssetStore.create(root);assert.equal((await store.read("models/players/test/lower.md3"))?.toString(),"custom");}finally{await rm(root,{recursive:true,force:true});}});
test("qpath allowlist rejects traversal, separators, and unrelated resources",()=>{assert.equal(validatePlayerQpath("models/players/test/head.md3"),"models/players/test/head.md3");for(const value of ["../secret","models/players/../secret.md3","models\\players\\test\\head.md3","scripts/test.shader","models/players/Test/head.md3"])assert.throws(()=>validatePlayerQpath(value));});
test("malformed and oversized ZIP metadata fails closed",()=>{assert.throws(()=>indexPk3(Buffer.from("not a zip")),/Malformed/);const bytes=zip({"models/players/test/a.tga":"x"}),entry=indexPk3(bytes).get("models/players/test/a.tga");assert.ok(entry);entry.uncompressed=40*1024*1024;assert.throws(()=>extractPk3Entry(bytes,entry),/limits/);});
test("containment rejects siblings and PK3 symlink escapes",async(t)=>{assert.equal(isPathContained(path.join("root","baseq3"),path.join("root","outside.pk3")),false);const root=await mkdtemp(path.join(tmpdir(),"q3-preview-link-"));try{const base=path.join(root,"baseq3"),outside=path.join(root,"outside.pk3");await mkdir(base);await writeFile(outside,zip({"models/players/test/lower.md3":"escaped"}));try{await symlink(outside,path.join(base,"pak0.pk3"),"file");}catch(error){if(process.platform==="win32"&&["EPERM","EACCES"].includes((error as NodeJS.ErrnoException).code??"")){t.skip("Windows symlink privilege unavailable");return;}throw error;}await assert.rejects(PlayerAssetStore.create(root),/Invalid PK3 archive/);}finally{await rm(root,{recursive:true,force:true});}});
