/*
 * This file is generated by jOOQ.
 */
package com.q3js.http.jooq.tables;


import com.q3js.http.jooq.DefaultSchema;
import com.q3js.http.jooq.Keys;
import com.q3js.http.jooq.tables.records.ServerRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Server extends TableImpl<ServerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>server</code>
     */
    public static final Server SERVER = new Server();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServerRecord> getRecordType() {
        return ServerRecord.class;
    }

    /**
     * The column <code>server.id</code>.
     */
    public final TableField<ServerRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>server.name</code>.
     */
    public final TableField<ServerRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>server.port</code>.
     */
    public final TableField<ServerRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>server.status</code>.
     */
    public final TableField<ServerRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>server.ip_address</code>.
     */
    public final TableField<ServerRecord, String> IP_ADDRESS = createField(DSL.name("ip_address"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>server.created_at</code>.
     */
    public final TableField<ServerRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Server(Name alias, Table<ServerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Server(Name alias, Table<ServerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>server</code> table reference
     */
    public Server(String alias) {
        this(DSL.name(alias), SERVER);
    }

    /**
     * Create an aliased <code>server</code> table reference
     */
    public Server(Name alias) {
        this(alias, SERVER);
    }

    /**
     * Create a <code>server</code> table reference
     */
    public Server() {
        this(DSL.name("server"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ServerRecord, Integer> getIdentity() {
        return (Identity<ServerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServerRecord> getPrimaryKey() {
        return Keys.SERVER_PKEY;
    }

    @Override
    public Server as(String alias) {
        return new Server(DSL.name(alias), this);
    }

    @Override
    public Server as(Name alias) {
        return new Server(alias, this);
    }

    @Override
    public Server as(Table<?> alias) {
        return new Server(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Server rename(String name) {
        return new Server(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Server rename(Name name) {
        return new Server(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Server rename(Table<?> name) {
        return new Server(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server where(Condition condition) {
        return new Server(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Server where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Server where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Server where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Server where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Server whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
