/*
 * This file is generated by jOOQ.
 */
package com.q3js.jooq;


import com.q3js.jooq.tables.Server;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>server</code>.
     */
    public static final Server SERVER = Server.SERVER;
}
