"use client";

import { useEffect, useRef, useState } from "react";
import { assemblePlayer, AssembledSurface, parseIdleFrames, parseMd3, parseSkin, parseTga, PlayerAppearance, playerResourcePaths } from "@/lib/player-model";
import { fetchFirstAvailable, isPlayerResourceNotFound, PlayerResourceHttpError, playerSkinCandidates } from "@/lib/player-preview";

type Status = "loading" | "ready" | "webgl" | "lost" | "error";
type DrawSurface = { position: WebGLBuffer; normal: WebGLBuffer; uv: WebGLBuffer; index: WebGLBuffer; texture: WebGLTexture; count: number };
type Resources = { program?: WebGLProgram; buffers: WebGLBuffer[]; textures: WebGLTexture[]; draws: DrawSurface[] };

const INITIAL_ROTATION = -0.55;
const INITIAL_PITCH = -0.12;
const INITIAL_ZOOM = 3.2;
const vertexShader = `attribute vec3 aPosition;attribute vec3 aNormal;attribute vec2 aUv;uniform mat4 uMvp;uniform mat4 uModel;varying vec2 vUv;varying float vLight;void main(){vec3 n=normalize((uModel*vec4(aNormal,0.)).xyz);vLight=.42+max(dot(n,normalize(vec3(-.35,-.55,.9))),0.)*.72;vUv=aUv;gl_Position=uMvp*vec4(aPosition,1.);}`;
const fragmentShader = `precision mediump float;uniform sampler2D uTexture;varying vec2 vUv;varying float vLight;void main(){vec4 c=texture2D(uTexture,vUv);if(c.a<.25)discard;gl_FragColor=vec4(c.rgb*vLight,c.a);}`;

function multiply(a: Float32Array, b: Float32Array): Float32Array { const result = new Float32Array(16); for (let column=0;column<4;column+=1) for (let row=0;row<4;row+=1) for (let index=0;index<4;index+=1) result[column*4+row]+=a[index*4+row]*b[column*4+index]; return result; }
function rotationZ(angle: number): Float32Array { const cosine=Math.cos(angle),sine=Math.sin(angle); return new Float32Array([cosine,sine,0,0,-sine,cosine,0,0,0,0,1,0,0,0,0,1]); }
function viewerMatrix(aspect: number, pitch: number, zoom: number): Float32Array { const near=.1,far=20,q=1/Math.tan(Math.PI/7.5),cosine=Math.cos(pitch),sine=Math.sin(pitch); return multiply(new Float32Array([q/Math.max(aspect,.01),0,0,0,0,q,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),new Float32Array([1,0,0,0,0,-sine,-cosine,0,0,cosine,-sine,0,0,0,-zoom,1])); }
function compile(gl: WebGLRenderingContext, type: number, source: string): WebGLShader { const shader=gl.createShader(type); if(!shader)throw new Error("Could not create shader"); gl.shaderSource(shader,source); gl.compileShader(shader); if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(shader)||"Could not compile shader";gl.deleteShader(shader);throw new Error(message);} return shader; }
function programFor(gl: WebGLRenderingContext): WebGLProgram { const vertex=compile(gl,gl.VERTEX_SHADER,vertexShader),fragment=compile(gl,gl.FRAGMENT_SHADER,fragmentShader),program=gl.createProgram(); if(!program){gl.deleteShader(vertex);gl.deleteShader(fragment);throw new Error("Could not create renderer");} gl.attachShader(program,vertex);gl.attachShader(program,fragment);gl.linkProgram(program);gl.deleteShader(vertex);gl.deleteShader(fragment);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){const message=gl.getProgramInfoLog(program)||"Could not link renderer";gl.deleteProgram(program);throw new Error(message);}return program; }
function bufferFor(gl: WebGLRenderingContext, target: number, data: ArrayBufferView<ArrayBufferLike>): WebGLBuffer { const result=gl.createBuffer();if(!result)throw new Error("Could not create geometry");const copy=new Uint8Array(data.byteLength);copy.set(new Uint8Array(data.buffer,data.byteOffset,data.byteLength));gl.bindBuffer(target,result);gl.bufferData(target,copy,gl.STATIC_DRAW);return result; }
async function fetchOne(qpath: string, signal: AbortSignal): Promise<Response> { const response=await fetch(`/api/player-resource?q=${encodeURIComponent(qpath)}`,{signal});if(!response.ok)throw new PlayerResourceHttpError(qpath,response.status);return response; }

async function loadAppearance(appearance: PlayerAppearance, signal: AbortSignal) {
  const paths=playerResourcePaths(appearance);let bodyRoot="",lower!:ArrayBuffer,upper!:ArrayBuffer,lowerSkin!:Map<string,string|null>,upperSkin!:Map<string,string|null>,animation="";
  for(const root of paths.bodyRoots)try{const lowerResponse=await fetchOne(`${root}/lower.md3`,signal),upperResponse=await fetchOne(`${root}/upper.md3`,signal),lowerSkinResponse=await fetchFirstAvailable(playerSkinCandidates(root,"lower",paths.bodySkin),signal),upperSkinResponse=await fetchFirstAvailable(playerSkinCandidates(root,"upper",paths.bodySkin),signal),animationResponse=await fetchOne(`${root}/animation.cfg`,signal);bodyRoot=root;lower=await lowerResponse.arrayBuffer();upper=await upperResponse.arrayBuffer();lowerSkin=parseSkin(await lowerSkinResponse.response.text());upperSkin=parseSkin(await upperSkinResponse.response.text());animation=await animationResponse.text();break;}catch(error){if(!isPlayerResourceNotFound(error)||root===paths.bodyRoots.at(-1))throw error;}
  if(!bodyRoot)throw new Error("Body model is not installed");
  let head!:ArrayBuffer,headSkin!:Map<string,string|null>;const headRoots=appearance.headModel.trim()?paths.headRoots:[bodyRoot];
  outer:for(const root of headRoots)for(const file of paths.headFileNames)try{const model=await fetchOne(`${root}/${file}`,signal),skin=await fetchFirstAvailable(playerSkinCandidates(root,"head",paths.headSkin,paths.separateHead),signal);head=await model.arrayBuffer();headSkin=parseSkin(await skin.response.text());break outer;}catch(error){if(!isPlayerResourceNotFound(error)||(root===headRoots.at(-1)&&file===paths.headFileNames.at(-1)))throw error;}
  const idle=parseIdleFrames(animation),surfaces=assemblePlayer(parseMd3(lower),parseMd3(upper),parseMd3(head),idle.lower,idle.upper,0);
  return{surfaces:surfaces.filter(surface=>(surface.part==="lower"?lowerSkin:surface.part==="upper"?upperSkin:headSkin).get(surface.name)!==null),skins:{lower:lowerSkin,upper:upperSkin,head:headSkin}};
}

function normalize(surfaces: AssembledSurface[]): void { const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const surface of surfaces)for(let index=0;index<surface.position.length;index+=3)for(let axis=0;axis<3;axis+=1){min[axis]=Math.min(min[axis],surface.position[index+axis]);max[axis]=Math.max(max[axis],surface.position[index+axis]);}const center=min.map((value,axis)=>(value+max[axis])/2),extent=Math.max(...max.map((value,axis)=>value-min[axis]),1);for(const surface of surfaces)for(let index=0;index<surface.position.length;index+=3)for(let axis=0;axis<3;axis+=1)surface.position[index+axis]=(surface.position[index+axis]-center[axis])*1.8/extent; }

async function textureFor(gl: WebGLRenderingContext, shader: string, signal: AbortSignal, active: ()=>boolean): Promise<WebGLTexture> {
  const hasExtension=/\.(tga|jpe?g|png|webp)$/i.test(shader),resource=await fetchFirstAvailable(hasExtension?[shader]:[`${shader}.tga`,`${shader}.jpg`,`${shader}.jpeg`,`${shader}.png`],signal),bytes=await resource.response.arrayBuffer();
  if(!active())throw new Error("Initialization superseded");
  let bitmap:ImageBitmap|undefined,imageData:ReturnType<typeof parseTga>|undefined;
  if(resource.path.endsWith(".tga"))imageData=parseTga(bytes);else bitmap=await createImageBitmap(new Blob([bytes],{type:resource.response.headers.get("content-type")||"image/jpeg"}));
  if(!active()){bitmap?.close();throw new Error("Initialization superseded");}
  const texture=gl.createTexture();if(!texture){bitmap?.close();throw new Error("Could not create texture");}
  try{gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);if(imageData){gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,0);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,imageData.width,imageData.height,0,gl.RGBA,gl.UNSIGNED_BYTE,imageData.pixels);}else if(bitmap){gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,bitmap);}gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.generateMipmap(gl.TEXTURE_2D);return texture;}catch(error){gl.deleteTexture(texture);throw error;}finally{bitmap?.close();}
}

export function PlayerModelViewer({model,skin,headModel,headSkin}:PlayerAppearance) {
  const canvasRef=useRef<HTMLCanvasElement>(null),viewportRef=useRef<HTMLDivElement>(null),rotation=useRef(INITIAL_ROTATION),pitch=useRef(INITIAL_PITCH),zoom=useRef(INITIAL_ZOOM),gesture=useRef<{id:number;x:number;y:number}|null>(null);
  const[status,setStatus]=useState<Status>("loading"),[retry,setRetry]=useState(0),[message,setMessage]=useState("");
  useEffect(()=>{
    const canvas=canvasRef.current,viewport=viewportRef.current;if(!canvas||!viewport)return;
    const gl=canvas.getContext("webgl",{alpha:true,antialias:true,powerPreference:"high-performance"});if(!gl){setStatus("webgl");return;}
    let disposed=false,contextLost=false,generation=0,frame=0,abort:AbortController|undefined,resources:Resources={buffers:[],textures:[],draws:[]};
    const release=(value:Resources)=>{for(const buffer of value.buffers)gl.deleteBuffer(buffer);for(const texture of value.textures)gl.deleteTexture(texture);if(value.program)gl.deleteProgram(value.program);value.buffers=[];value.textures=[];value.draws=[];value.program=undefined;};
    const supersede=()=>{generation+=1;cancelAnimationFrame(frame);abort?.abort();abort=undefined;release(resources);resources={buffers:[],textures:[],draws:[]};};
    const initialize=async()=>{
      supersede();const current=generation;abort=new AbortController();const signal=abort.signal,created:Resources={buffers:[],textures:[],draws:[]};const active=()=>!disposed&&!contextLost&&!signal.aborted&&generation===current;
      setStatus("loading");setMessage("");
      try{
        const loaded=await loadAppearance({model,skin,headModel,headSkin},signal);if(!active())return;normalize(loaded.surfaces);created.program=programFor(gl);
        for(const surface of loaded.surfaces){if(!active())throw new Error("Initialization superseded");const shader=loaded.skins[surface.part].get(surface.name);if(shader===undefined)throw new Error(`Skin has no mapping for surface ${surface.name}`);if(shader===null)continue;const texture=await textureFor(gl,shader,signal,active);created.textures.push(texture);if(!active())throw new Error("Initialization superseded");const position=bufferFor(gl,gl.ARRAY_BUFFER,surface.position);created.buffers.push(position);const normal=bufferFor(gl,gl.ARRAY_BUFFER,surface.normal);created.buffers.push(normal);const uv=bufferFor(gl,gl.ARRAY_BUFFER,surface.uvs);created.buffers.push(uv);const index=bufferFor(gl,gl.ELEMENT_ARRAY_BUFFER,surface.indices);created.buffers.push(index);created.draws.push({position,normal,uv,index,texture,count:surface.indices.length});}
        if(!created.draws.length)throw new Error("Selected skin disables every surface");if(!active())throw new Error("Initialization superseded");resources=created;
        const program=created.program,position=gl.getAttribLocation(program,"aPosition"),normal=gl.getAttribLocation(program,"aNormal"),uv=gl.getAttribLocation(program,"aUv"),mvp=gl.getUniformLocation(program,"uMvp"),modelUniform=gl.getUniformLocation(program,"uModel");gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.useProgram(program);gl.uniform1i(gl.getUniformLocation(program,"uTexture"),0);let previous=performance.now();
        const render=(now:number)=>{if(!active())return;if(!gesture.current&&!matchMedia("(prefers-reduced-motion: reduce)").matches)rotation.current+=Math.min(now-previous,40)*.00018;previous=now;const matrix=rotationZ(rotation.current);gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(mvp,false,multiply(viewerMatrix(canvas.width/Math.max(canvas.height,1),pitch.current,zoom.current),matrix));gl.uniformMatrix4fv(modelUniform,false,matrix);for(const draw of created.draws){gl.bindTexture(gl.TEXTURE_2D,draw.texture);gl.bindBuffer(gl.ARRAY_BUFFER,draw.position);gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,draw.normal);gl.enableVertexAttribArray(normal);gl.vertexAttribPointer(normal,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,draw.uv);gl.enableVertexAttribArray(uv);gl.vertexAttribPointer(uv,2,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,draw.index);gl.drawElements(gl.TRIANGLES,draw.count,gl.UNSIGNED_SHORT,0);}frame=requestAnimationFrame(render);};
        setStatus("ready");frame=requestAnimationFrame(render);
      }catch(error){release(created);if(active()){setMessage(error instanceof Error?error.message:"Selected player could not be loaded");setStatus("error");}}
    };
    const resize=()=>{const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(viewport.clientWidth*ratio));canvas.height=Math.max(1,Math.round(viewport.clientHeight*ratio));};const observer=new ResizeObserver(resize);observer.observe(viewport);resize();
    const wheel=(event:WheelEvent)=>{if(document.activeElement!==canvas)return;zoom.current=Math.min(5,Math.max(2.55,zoom.current+event.deltaY*.003));event.preventDefault();};
    const lost=(event:Event)=>{event.preventDefault();contextLost=true;supersede();if(!disposed)setStatus("lost");};
    const restored=()=>{if(disposed)return;contextLost=false;void initialize();};
    canvas.addEventListener("wheel",wheel,{passive:false});canvas.addEventListener("webglcontextlost",lost);canvas.addEventListener("webglcontextrestored",restored);void initialize();
    return()=>{disposed=true;observer.disconnect();supersede();canvas.removeEventListener("wheel",wheel);canvas.removeEventListener("webglcontextlost",lost);canvas.removeEventListener("webglcontextrestored",restored);};
  },[model,skin,headModel,headSkin,retry]);
  const reset=()=>{rotation.current=INITIAL_ROTATION;pitch.current=INITIAL_PITCH;zoom.current=INITIAL_ZOOM;};
  return <div className="player-viewer"><div ref={viewportRef} className="player-viewer-viewport"><div className="weapon-viewer-grid" aria-hidden="true"/><canvas ref={canvasRef} className="player-viewer-canvas" tabIndex={0} role="img" aria-label={`Interactive 3D preview of ${model||"selected"} player model`} onKeyDown={event=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();rotation.current+=event.key==="ArrowLeft"?-.12:.12;}else if(event.key==="ArrowUp"||event.key==="ArrowDown"){event.preventDefault();zoom.current=Math.min(5,Math.max(2.55,zoom.current+(event.key==="ArrowUp"?-.18:.18)));}else if(event.key==="Home"||event.key==="0"){event.preventDefault();reset();}}} onPointerDown={event=>{if(event.pointerType==="mouse"&&event.button!==0)return;event.currentTarget.focus();event.currentTarget.setPointerCapture(event.pointerId);gesture.current={id:event.pointerId,x:event.clientX,y:event.clientY};}} onPointerMove={event=>{const current=gesture.current;if(!current||current.id!==event.pointerId)return;rotation.current+=(event.clientX-current.x)*.012;pitch.current=Math.min(.38,Math.max(-.42,pitch.current+(event.clientY-current.y)*.006));current.x=event.clientX;current.y=event.clientY;}} onPointerUp={event=>{if(gesture.current?.id===event.pointerId)gesture.current=null;}} onPointerCancel={()=>{gesture.current=null;}}/>{status!=="ready"?<div className="player-viewer-status" role="status"><span>{status==="loading"?"Loading installed player model…":status==="webgl"?"WebGL is unavailable.":status==="lost"?"3D context lost. Restoring…":message||"Selected player could not be loaded."}</span>{status==="error"||status==="lost"?<button type="button" className="bot-button" onClick={()=>setRetry(value=>value+1)}>Retry preview</button>:null}</div>:null}</div><div className="player-viewer-toolbar"><p>Actual installed model and skin · Drag to turn · Focus + wheel to zoom</p><button type="button" className="bot-button" onClick={reset}>Reset view</button></div></div>;
}
