#include "chars.h"

skill 1
{
 CHARACTERISTIC_NAME "GUY"
 CHARACTERISTIC_GENDER "male"
 CHARACTERISTIC_ATTACK_SKILL 0.25
 CHARACTERISTIC_AIM_SKILL 0.20
 CHARACTERISTIC_AIM_ACCURACY 0.20
 CHARACTERISTIC_REACTIONTIME 0.85
 CHARACTERISTIC_VIEW_FACTOR 0.35
 CHARACTERISTIC_VIEW_MAXCHANGE 180
 CHARACTERISTIC_CHAT_FILE "bots/hunter_t.c"
 CHARACTERISTIC_CHAT_NAME "hunter"
 CHARACTERISTIC_ITEMWEIGHTS "bots/hunter_i.c"
 CHARACTERISTIC_WEAPONWEIGHTS "bots/hunter_w.c"
}
skill 4
{
 CHARACTERISTIC_NAME "GUY"
 CHARACTERISTIC_GENDER "male"
 CHARACTERISTIC_ATTACK_SKILL 0.85
 CHARACTERISTIC_AIM_SKILL 0.82
 CHARACTERISTIC_AIM_ACCURACY 0.78
 CHARACTERISTIC_REACTIONTIME 0.18
 CHARACTERISTIC_VIEW_FACTOR 0.78
 CHARACTERISTIC_VIEW_MAXCHANGE 300
 CHARACTERISTIC_CHAT_FILE "bots/hunter_t.c"
 CHARACTERISTIC_CHAT_NAME "hunter"
 CHARACTERISTIC_ITEMWEIGHTS "bots/hunter_i.c"
 CHARACTERISTIC_WEAPONWEIGHTS "bots/hunter_w.c"
}
skill 5
{
 CHARACTERISTIC_NAME "GUY"
 CHARACTERISTIC_GENDER "male"
 CHARACTERISTIC_ATTACK_SKILL 1.0
 CHARACTERISTIC_AIM_SKILL 1.0
 CHARACTERISTIC_AIM_ACCURACY 0.98
 CHARACTERISTIC_REACTIONTIME 0.02
 CHARACTERISTIC_VIEW_FACTOR 0.98
 CHARACTERISTIC_VIEW_MAXCHANGE 360
 CHARACTERISTIC_CHAT_FILE "bots/hunter_t.c"
 CHARACTERISTIC_CHAT_NAME "hunter"
 CHARACTERISTIC_ITEMWEIGHTS "bots/hunter_i.c"
 CHARACTERISTIC_WEAPONWEIGHTS "bots/hunter_w.c"
}
